
package forms;

import clasesUtiles.Comparador;
import clasesUtiles.ComparadorCiudad;
import clasesUtiles.ControlLetr;
import clasesUtiles.ControlNum;
import clasesUtiles.ModeloTabla;
import clasesUtiles.Util;
import entidades.Ciudad;
import entidades.Pasaje;
import entidades.Pasajero;
import entidades.Trayecto;
import entidades.Viaje;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.persistence.EntityExistsException;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;


public class frmPasajes extends javax.swing.JFrame {

    EntityManagerFactory emf;
    EntityManager em;
    ArrayList<Ciudad> ciudades = new ArrayList<Ciudad>();    
    boolean flag=true;  
    public static Viaje viaje;
    Pasajero pasajero;
    public static JTextField txtAsient;
    private int unidadPrecio;
    
    public frmPasajes() {
        initComponents();
        emf= Persistence.createEntityManagerFactory("colectivos.odb");
        em = emf.createEntityManager();
        txtCI.setDocument(new ControlNum(7));
        txtNombre.setDocument(new ControlLetr(16));
        txtApellido.setDocument(new ControlLetr(16));
        jDCPasaje.setEnabled(false);
        jDCPasaje.getCalendarButton().setEnabled(true);
        jDCPasaje.setDate(new java.util.Date());
        cargarCmbViaje();
        cargarDetalleViaje();// una vez llamado este metodo ya tenemos disponible el objeto "viaje"
        cargarCombosC();
        cargarTablaC();
        calcularMonto();
        txtAsient = txtAsiento;
        unidadPrecio=5000;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDCPasaje = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNro = new javax.swing.JTextField();
        lbTrayecto = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaC = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbViaje = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbInicio = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        cmbFin = new javax.swing.JComboBox();
        lbDetalle = new javax.swing.JLabel();
        lbDetalle1 = new javax.swing.JLabel();
        txtFechaViaje = new javax.swing.JTextField();
        lbDetalle2 = new javax.swing.JLabel();
        txtHoraViaje = new javax.swing.JTextField();
        txtVeh = new javax.swing.JTextField();
        lbVehiculo = new javax.swing.JLabel();
        lbPasajes = new javax.swing.JLabel();
        txtPasajes = new javax.swing.JTextField();
        txtTrayecto = new javax.swing.JTextField();
        lbTrayecto1 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAsiento = new javax.swing.JTextField();
        btnAsiento = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pasajes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pasaje:");

        jLabel2.setText("Fecha:");

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirmar.png"))); // NOI18N
        btnGuardar.setToolTipText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        btnCancelar.setToolTipText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Right32Green.png"))); // NOI18N
        btnCerrar.setToolTipText("Cerrar ventana");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Nro:");

        txtNro.setEnabled(false);

        lbTrayecto.setText("Trayecto:");

        tablaC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaC);

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adicionar.png"))); // NOI18N
        btnNuevo.setToolTipText("Añadir Ciudad");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        jLabel6.setText("Cedula:");

        txtNombre.setEnabled(false);

        jLabel7.setText("Apellido");

        txtApellido.setEnabled(false);

        jLabel8.setText("Nombre:");

        txtCI.setToolTipText("Presione enter");
        txtCI.setEnabled(false);
        txtCI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCIKeyPressed(evt);
            }
        });

        jLabel4.setText("Viaje:");

        cmbViaje.setEnabled(false);
        cmbViaje.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbViajePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel5.setText("Inicio:");

        cmbInicio.setEnabled(false);

        jLabel9.setText("Fin:");

        cmbFin.setEnabled(false);
        cmbFin.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbFinPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        lbDetalle.setText("Detalles de Viaje:");

        lbDetalle1.setText("Fecha:");

        txtFechaViaje.setEnabled(false);

        lbDetalle2.setText("Hora:");

        txtHoraViaje.setEnabled(false);

        txtVeh.setEnabled(false);

        lbVehiculo.setText("Vehiculo:");

        lbPasajes.setText("Pasajes:");

        txtPasajes.setEnabled(false);

        txtTrayecto.setEnabled(false);

        lbTrayecto1.setText("Estado:");

        txtEstado.setEnabled(false);

        jLabel10.setText("Asiento:");

        txtAsiento.setEnabled(false);

        btnAsiento.setText("-->");
        btnAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsientoActionPerformed(evt);
            }
        });

        jLabel11.setText("Monto:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNro)
                                            .addComponent(txtCI)
                                            .addComponent(cmbViaje, 0, 108, Short.MAX_VALUE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbDetalle1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaViaje))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbDetalle2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHoraViaje)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbInicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtNombre)
                                            .addComponent(jDCPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                        .addGap(34, 34, 34)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbFin, 0, 160, Short.MAX_VALUE)
                                            .addComponent(txtApellido))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnAsiento))
                                            .addComponent(txtMonto)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbPasajes)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPasajes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbVehiculo)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbTrayecto1)
                                                .addGap(24, 24, 24)
                                                .addComponent(txtEstado))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lbTrayecto)
                                                .addGap(12, 12, 12)
                                                .addComponent(txtTrayecto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 10, Short.MAX_VALUE))
                            .addComponent(jSeparator1))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lbDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDCPasaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmbViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAsiento)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lbDetalle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbDetalle1)
                                .addComponent(txtFechaViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbVehiculo)
                                .addComponent(txtVeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTrayecto)
                                .addComponent(txtTrayecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbDetalle2)
                                .addComponent(txtHoraViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbPasajes)
                                .addComponent(txtPasajes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTrayecto1)
                                .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(108, 108, 108))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNuevo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCerrar)))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Pasaje pasaje;
        if(txtCI.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar datos");
            txtCI.requestFocusInWindow();
            return;
        }

        if(txtMonto.getText().equals("")||Integer.parseInt(txtMonto.getText())==0){
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar monto");
            txtMonto.requestFocusInWindow();
            return;
        }
        
        if(txtAsiento.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar asiento");
            btnAsiento.requestFocusInWindow();
            return;
        }        
        
        if(pasajero==null){
            em.getTransaction().begin();
            pasajero= new Pasajero(Integer.parseInt(txtCI.getText()),
                                    txtNombre.getText(),
                                    txtApellido.getText());
            em.persist(pasajero);
            em.getTransaction().commit();
            pasajero= em.find(Pasajero.class, Integer.parseInt(txtCI.getText()));
        }
        if (flag){
            try{
                em.getTransaction().begin();
                pasaje = new Pasaje(Util.utilToSql(jDCPasaje.getDate()),
                                    pasajero,
                                    viaje,
                                    cmbInicio.getSelectedItem().toString(),
                                    cmbFin.getSelectedItem().toString());
        
                
                pasaje.setMonto(Integer.parseInt(txtMonto.getText()));
                em.persist(pasaje);
                em.getTransaction().commit();
                
                em.getTransaction().begin();
                viaje.getAsientos().set(Integer.parseInt(txtAsiento.getText())-1, false);
                
                em.getTransaction().commit();
            }catch(EntityExistsException ex){
                JOptionPane.showMessageDialog(rootPane, "Ya se encuentra registrado");
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error al guardar" + e.getMessage());
            }
        }else{
//            int id=Integer.parseInt(txtNro.getText());
//            em.getTransaction().begin();
//            via = em.find(Viaje.class, id);
//            via.setFechaViaje(Util.utilToSql(jDCPasaje.getDate()));
//            via.setHoraViaje(sqlTim);
//            via.setTrayecto(trayec);
//            via.setVehiculo(veh);
//            via.setEstado(cmbEstado.getSelectedItem().toString());
//            
//            em.getTransaction().commit();
        }
        txtNro.setText(null);
        jDCPasaje.setDate(new java.util.Date());
        cmbInicio.setSelectedIndex(0);
        cmbFin.setSelectedIndex(0);
        cargarCmbViaje();
        cargarDetalleViaje();// una vez llamado este metodo ya tenemos disponible el objeto "viaje"
        cargarCombosC();
        cargarTablaC();
        calcularMonto();
        cmbInicio.setEnabled(false);
        cmbFin.setEnabled(false);
        txtVeh.setText(null);
        txtPasajes.setText(null);
        txtNombre.setText(null);
        txtApellido.setText(null);
        txtAsiento.setText(null);
        txtPasajes.setEnabled(false);
        txtNombre.setEnabled(false);
        txtApellido.setEnabled(false);
        
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);

        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        txtNro.setText(null);
        jDCPasaje.setDate(new java.util.Date());
        cmbViaje.setEnabled(false);
        try{
            cmbInicio.setSelectedIndex(0);
            cmbFin.setSelectedIndex(0);
        }catch(IllegalArgumentException ex){
        
        }
        cmbInicio.setEnabled(false);
        cmbFin.setEnabled(false);
        txtVeh.setText(null);
        txtPasajes.setText(null);
        btnGuardar.setEnabled(false);
        btnNuevo.setEnabled(true);
        
        cargarCmbViaje();
        cargarDetalleViaje();// una vez llamado este metodo ya tenemos disponible el objeto "viaje"
        cargarCombosC();
        cargarTablaC();        

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        flag= true;
        txtNro.setText(null);
        jDCPasaje.setDate(new java.util.Date());
        txtCI.setEnabled(true);
        txtCI.requestFocusInWindow();
        cmbViaje.setEnabled(true);
        cmbInicio.setEnabled(true);
        cmbFin.setEnabled(true);
        cargarCmbViaje();
        cargarTablaC();
        txtVeh.setText(null);
        txtPasajes.setText(null);
        btnGuardar.setEnabled(true);
        btnNuevo.setEnabled(false);
        
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cmbViajePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbViajePopupMenuWillBecomeInvisible
        cargarDetalleViaje();// una vez llamado este metodo ya tenemos disponible el objeto "viaje"
        cargarCombosC();
        cargarTablaC();
        txtMonto.setText(null);
    }//GEN-LAST:event_cmbViajePopupMenuWillBecomeInvisible

    private void txtCIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCIKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER) {
            buscarPasajero();
            if(pasajero!=null){
                txtNombre.setText(pasajero.getNombre());        
                txtApellido.setText(pasajero.getApellido());
                txtNombre.setEnabled(false);
                txtApellido.setEnabled(false);
            }else{
                txtNombre.setEnabled(true);
                txtApellido.setEnabled(true);
                txtNombre.requestFocusInWindow();
            }
        }
    }//GEN-LAST:event_txtCIKeyPressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        em.flush();
        em.close();
        emf.close();
    }//GEN-LAST:event_formWindowClosed

    private void btnAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsientoActionPerformed
        new frmAsientos().setVisible(true);
    }//GEN-LAST:event_btnAsientoActionPerformed

    private void cmbFinPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbFinPopupMenuWillBecomeInvisible
        calcularMonto();
    }//GEN-LAST:event_cmbFinPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPasajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPasajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsiento;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox cmbFin;
    private javax.swing.JComboBox cmbInicio;
    private javax.swing.JComboBox cmbViaje;
    private com.toedter.calendar.JDateChooser jDCPasaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbDetalle;
    private javax.swing.JLabel lbDetalle1;
    private javax.swing.JLabel lbDetalle2;
    private javax.swing.JLabel lbPasajes;
    private javax.swing.JLabel lbTrayecto;
    private javax.swing.JLabel lbTrayecto1;
    private javax.swing.JLabel lbVehiculo;
    private javax.swing.JTable tablaC;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtAsiento;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaViaje;
    private javax.swing.JTextField txtHoraViaje;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNro;
    private javax.swing.JTextField txtPasajes;
    private javax.swing.JTextField txtTrayecto;
    private javax.swing.JTextField txtVeh;
    // End of variables declaration//GEN-END:variables


    public void cargarCmbViaje(){
        cmbViaje.removeAllItems();
        TypedQuery<Viaje> q1 = em.createQuery("SELECT via FROM Viaje via ORDER BY via.idViaje DESC", Viaje.class);
        
        List<Viaje> results = q1.setMaxResults(30).getResultList();
        for(Viaje v: results){
            cmbViaje.addItem(v.getIdViaje());
        }        
    }
    
    public void cargarDetalleViaje(){
            try{
            Query query = em.createQuery("SELECT v FROM Viaje v WHERE v.idViaje = " + cmbViaje.getSelectedItem().toString());
            viaje = (Viaje) query.getSingleResult();
            String modo= viaje.isModo()?"ida":"vuelta"; //operador ternario, pregunta es true? devuelve el primero
            txtFechaViaje.setText(clasesUtiles.Util.sqlDateToStr(viaje.getFechaViaje()));
            txtHoraViaje.setText(viaje.getHoraViaje().toString());
            txtVeh.setText(String.valueOf(viaje.getVehiculo().getNro()));
            txtPasajes.setText(Util.pasajesVia(viaje.getAsientos()));
            txtTrayecto.setText(String.valueOf(viaje.getTrayecto().getIdTrayecto()) +" "+modo);
            txtEstado.setText(viaje.getEstado());
            }catch(NullPointerException ex){
            
            }
    }
    
        private void cargarTablaC() {
        ArrayList datos = new ArrayList();
        String[] cols = new String[]{"Id","Ciudad", "Orden"};              
        try{
            datos.clear();

            for(Ciudad c: viaje.getTrayecto().getCiudades()){
                datos.add(new Object[]{c.getIdCiudad(),c.getNombre(), c.getOrden()});
            }
            Collections.sort(datos, new Comparador());
        }
        catch(Exception ex){
            System.out.println(ex.getClass().getName());
            System.out.println(ex.getMessage());
            return;        
        }
         ModeloTabla modelo= new ModeloTabla(datos, cols);
        tablaC.setModel(modelo);
        tablaC.getColumnModel().getColumn(0).setMinWidth(0);
        tablaC.getColumnModel().getColumn(0).setPreferredWidth(0);
        tablaC.getColumnModel().getColumn(0).setResizable(false);
        tablaC.getColumnModel().getColumn(1).setPreferredWidth(140);
        tablaC.getColumnModel().getColumn(1).setResizable(false);
        tablaC.getColumnModel().getColumn(2).setPreferredWidth(50);
        tablaC.getColumnModel().getColumn(2).setResizable(false);        
        tablaC.getTableHeader().setReorderingAllowed(true);
        tablaC.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tablaC.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);            
    }
        
        public void cargarCombosC(){
            try{
                ciudades.clear();
                cmbInicio.removeAllItems();
                cmbFin.removeAllItems();
                for(Ciudad c: viaje.getTrayecto().getCiudades()){
                    ciudades.add(c);
                }
                Collections.sort(ciudades, new ComparadorCiudad());
                //agregar condicion ida o vuelta y aplicar metodo reverse
                if(!viaje.isModo()) Collections.reverse(ciudades); //en caso de que el viaje sea de retorno
                for(int i=0; i< ciudades.size(); i++){
                    cmbInicio.addItem(ciudades.get(i).getNombre());
                    cmbFin.addItem(ciudades.get(i).getNombre());
                }
            }catch(NullPointerException ex){
            
            }
        }

    private void buscarPasajero() {
        int ci= Integer.parseInt(txtCI.getText());
        pasajero= em.find(Pasajero.class, ci);
    }

    private void calcularMonto() {
        int ciuInicio;
        int ciuFin;
        int monto=0;
        int pasos=0;
        boolean band= false;
        try{
            ciuInicio= ciudades.indexOf(retornaCiu(cmbInicio.getSelectedItem().toString()));
            ciuFin= ciudades.indexOf(retornaCiu(cmbFin.getSelectedItem().toString()));
            pasos= ciuFin - ciuInicio;
            monto =pasos * unidadPrecio;
            txtMonto.setText(String.valueOf(monto));
        }catch(NullPointerException ex){
        
        }
    }
    
    private Ciudad retornaCiu(String nombreC){
        Query query = em.createQuery("SELECT c FROM Ciudad c WHERE c.nombre = '" + nombreC+"'");
        Ciudad ciu= (Ciudad) query.getSingleResult();
        return ciu;
    }
    
}
